#!/usr/bin/env python3
"""Build a normalized import plan from a JsTun legacy export snapshot."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any


DEFAULT_EDGES = [
    {
        "edge_id": "edg",
        "name": "EDG",
        "role": "gateway",
        "state": "enabled",
        "description": "Primary gateway edge",
    },
    {
        "edge_id": "vrn",
        "name": "VRN",
        "role": "gateway",
        "state": "enabled",
        "description": "Secondary gateway edge",
    },
]

DEFAULT_UPLINKS = [
    {
        "uplink_id": "edg/ams",
        "edge_id": "edg",
        "name": "ams",
        "kind": "wireguard",
        "enabled": True,
        "description": None,
    },
    {
        "uplink_id": "edg/fra",
        "edge_id": "edg",
        "name": "fra",
        "kind": "wireguard",
        "enabled": True,
        "description": None,
    },
    {
        "uplink_id": "edg/nyc",
        "edge_id": "edg",
        "name": "nyc",
        "kind": "wireguard",
        "enabled": True,
        "description": None,
    },
    {
        "uplink_id": "vrn/ams",
        "edge_id": "vrn",
        "name": "ams",
        "kind": "wireguard",
        "enabled": True,
        "description": "wg-ams / table vrn-ams / mark 0x11",
    },
    {
        "uplink_id": "vrn/fra",
        "edge_id": "vrn",
        "name": "fra",
        "kind": "wireguard",
        "enabled": True,
        "description": "wg-fra / table vrn-fra / mark 0x13",
    },
    {
        "uplink_id": "vrn/nyc",
        "edge_id": "vrn",
        "name": "nyc",
        "kind": "wireguard",
        "enabled": True,
        "description": "wg-nyc / table vrn-nyc / mark 0x12",
    },
]

ALLOWED_STATUSES = {"pending", "active", "blocked", "expired", "removed"}
DEFAULT_SKIPPED_STATUSES = {"blocked", "expired", "removed"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a normalized import plan from a JsTun legacy export snapshot."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to JSON snapshot generated by legacy_export.py",
    )
    parser.add_argument(
        "--output",
        help="Write import plan JSON to this file instead of stdout.",
    )
    parser.add_argument(
        "--default-edge-id",
        default="edg",
        help="Bootstrap ingress edge for imported peers.",
    )
    parser.add_argument(
        "--default-policy-mode",
        default="ams",
        help="Bootstrap routing policy mode for imported peers.",
    )
    parser.add_argument(
        "--default-preferred-uplink-id",
        default="edg/ams",
        help="Bootstrap preferred uplink for imported peers.",
    )
    parser.add_argument(
        "--default-failover-uplink-id",
        default="edg/fra",
        help="Bootstrap failover uplink for imported peers.",
    )
    parser.add_argument(
        "--skip-status",
        action="append",
        default=[],
        help=(
            "Peer status to exclude from working peer import. "
            "May be passed multiple times. Defaults to blocked, expired, removed."
        ),
    )
    return parser.parse_args()


def read_snapshot(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text())
    if payload.get("format") != "jstun-control-plane-legacy-export/v1":
        raise ValueError(f"unsupported snapshot format: {payload.get('format')!r}")
    return payload


def parse_metadata_blob(raw: Any) -> dict[str, Any]:
    if raw in (None, ""):
        return {}
    if isinstance(raw, dict):
        return raw
    if not isinstance(raw, str):
        return {"_raw": raw}
    try:
        decoded = json.loads(raw)
    except json.JSONDecodeError:
        return {"_raw": raw}
    return decoded if isinstance(decoded, dict) else {"_raw": decoded}


def normalize_amount_minor(raw: Any) -> int | None:
    if raw in (None, ""):
        return None
    try:
        return int((Decimal(str(raw)) * 100).quantize(Decimal("1")))
    except (InvalidOperation, ValueError):
        return None


def normalize_billing_status(raw: Any) -> str | None:
    if not isinstance(raw, str) or not raw:
        return None
    value = raw.strip().lower()
    mapping = {
        "paid": "paid",
        "success": "paid",
        "pending": "pending",
        "created": "pending",
        "expired": "expired",
        "failed": "failed",
        "cancelled": "cancelled",
        "canceled": "cancelled",
    }
    return mapping.get(value, "unknown")


def transform_peer(
    row: dict[str, Any],
    label_overrides: dict[str, str],
    type_overrides: dict[str, str],
    args: argparse.Namespace,
    quarantine: list[dict[str, Any]],
) -> tuple[dict[str, Any] | None, dict[str, Any] | None, dict[str, Any] | None]:
    source = row.get("source")
    if not isinstance(source, dict):
        quarantine.append(
            {
                "kind": "invalid_peer_source",
                "peer_id": row.get("peer_id"),
                "reason": "expected_object",
            }
        )
        return None, None, None

    peer_id = row["peer_id"]
    status = source.get("status")
    if status not in ALLOWED_STATUSES:
        quarantine.append(
            {
                "kind": "invalid_peer_status",
                "peer_id": peer_id,
                "value": status,
            }
        )
        return None, None, None

    label = label_overrides.get(peer_id) or source.get("label") or peer_id
    peer_type = type_overrides.get(peer_id, "default")

    peer = {
        "peer_id": peer_id,
        "label": label,
        "peer_type": peer_type,
        "status": status,
        "public_key": source.get("public_key"),
        "allowed_ip": source.get("allowed_ip"),
        "endpoint": source.get("endpoint"),
        "created_at": source.get("created_at"),
        "pending_expires_at": source.get("expires_at"),
        "ttl_sec": source.get("ttl_sec"),
        "absolute_ttl_sec": None,
        "absolute_expires_at": None,
        "lk_token": source.get("lk_token"),
        "lk_token_created_at": source.get("lk_token_created_at"),
        "connected_at": None,
        "blocked_at": source.get("blocked_at"),
        "block_reason": source.get("block_reason"),
        "removed_at": source.get("removed_at"),
        "remove_reason": source.get("remove_reason"),
        "created_by": "legacy-import",
        "updated_at": source.get("removed_at") or source.get("expires_at") or source.get("created_at"),
        "legacy_file_name": row.get("file_name"),
    }

    routing_policy = {
        "peer_id": peer_id,
        "ingress_edge_id": args.default_edge_id,
        "policy_mode": args.default_policy_mode,
        "preferred_uplink_id": args.default_preferred_uplink_id,
        "failover_uplink_id": args.default_failover_uplink_id,
        "updated_at": source.get("removed_at") or source.get("expires_at") or source.get("created_at"),
        "updated_by": "legacy-import",
        "change_reason": "bootstrap_from_legacy_state",
    }

    runtime_state = {
        "peer_id": peer_id,
        "last_handshake_at": None,
        "last_handshake_unix": None,
        "rx_bytes": 0,
        "tx_bytes": 0,
        "real_ip": None,
        "active_uplink_id": None,
        "health_status": "unknown",
        "health_note": "legacy import without runtime snapshot",
        "observed_at": source.get("removed_at") or source.get("expires_at") or source.get("created_at"),
    }
    return peer, routing_policy, runtime_state


def transform_billing(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result = []
    for row in rows:
        result.append(
            {
                "peer_id": row.get("peer_id"),
                "provider": row.get("provider"),
                "provider_order_id": row.get("external_id"),
                "status_raw": row.get("status"),
                "status_normalized": normalize_billing_status(row.get("status")),
                "amount_minor": normalize_amount_minor(row.get("amount_rub")),
                "currency": row.get("currency"),
                "payment_url": row.get("payment_url"),
                "purpose": row.get("purpose"),
                "created_at": row.get("created_at"),
                "updated_at": row.get("updated_at"),
                "expires_at": row.get("expires_at"),
                "paid_at": row.get("paid_at"),
                "error_code": row.get("error_code"),
                "error_message": row.get("error_message"),
                "metadata": {
                    "provider_status": row.get("provider_status"),
                    **parse_metadata_blob(row.get("meta_json")),
                },
                "legacy_billing_order_id": row.get("id"),
            }
        )
    return result


def transform_events(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result = []
    for row in rows:
        metadata = {k: v for k, v in row.items() if k not in {"ts", "event", "peer_id", "reason"}}
        result.append(
            {
                "event_type": row.get("event"),
                "occurred_at": row.get("ts"),
                "actor_type": "legacy-http",
                "actor_id": metadata.get("ip"),
                "peer_id": row.get("peer_id") or None,
                "edge_id": None,
                "uplink_id": None,
                "request_id": None,
                "reason": row.get("reason"),
                "old_value": None,
                "new_value": None,
                "metadata": metadata,
            }
        )
    return result


def build_import_plan(snapshot: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    quarantine = list(snapshot.get("quarantine", []))
    label_overrides = snapshot.get("label_overrides", {})
    type_overrides = snapshot.get("type_overrides", {})
    skipped_statuses = set(args.skip_status) | DEFAULT_SKIPPED_STATUSES

    peers: list[dict[str, Any]] = []
    routing_policies: list[dict[str, Any]] = []
    peer_runtime_state: list[dict[str, Any]] = []
    skipped_peers: list[dict[str, Any]] = []
    seen_public_keys: dict[str, str] = {}
    seen_lk_tokens: dict[str, str] = {}

    for row in snapshot.get("peers", []):
        peer, routing_policy, runtime_state = transform_peer(
            row, label_overrides, type_overrides, args, quarantine
        )
        if peer is None:
            continue

        if peer["status"] in skipped_statuses:
            skipped_peers.append(
                {
                    "peer_id": peer["peer_id"],
                    "status": peer["status"],
                    "reason": "status_excluded_from_working_import",
                    "legacy_file_name": peer.get("legacy_file_name"),
                    "label": peer.get("label"),
                }
            )
            continue

        public_key = peer.get("public_key")
        if public_key in seen_public_keys:
            quarantine.append(
                {
                    "kind": "duplicate_public_key",
                    "peer_id": peer["peer_id"],
                    "duplicate_of": seen_public_keys[public_key],
                    "value": public_key,
                }
            )
            continue
        if public_key:
            seen_public_keys[public_key] = peer["peer_id"]

        lk_token = peer.get("lk_token")
        if lk_token in seen_lk_tokens:
            quarantine.append(
                {
                    "kind": "duplicate_lk_token",
                    "peer_id": peer["peer_id"],
                    "duplicate_of": seen_lk_tokens[lk_token],
                    "value": lk_token,
                }
            )
            continue
        if lk_token:
            seen_lk_tokens[lk_token] = peer["peer_id"]

        peers.append(peer)
        routing_policies.append(routing_policy)
        peer_runtime_state.append(runtime_state)

    peer_ids = {row["peer_id"] for row in peers}
    billing_records = []
    for row in transform_billing(snapshot.get("billing", {}).get("rows", [])):
        if row["peer_id"] not in peer_ids:
            quarantine.append(
                {
                    "kind": "orphaned_billing_row",
                    "legacy_billing_order_id": row.get("legacy_billing_order_id"),
                    "peer_id": row.get("peer_id"),
                }
            )
        billing_records.append(row)

    events = transform_events(snapshot.get("audit", {}).get("events", []))

    for peer_id in label_overrides:
        if peer_id not in peer_ids:
            quarantine.append(
                {
                    "kind": "orphaned_label_override",
                    "peer_id": peer_id,
                    "value": label_overrides[peer_id],
                }
            )
    for peer_id in type_overrides:
        if peer_id not in peer_ids:
            quarantine.append(
                {
                    "kind": "orphaned_type_override",
                    "peer_id": peer_id,
                    "value": type_overrides[peer_id],
                }
            )

    status_distribution = dict(Counter(row["status"] for row in peers))

    return {
        "format": "jstun-control-plane-import-plan/v1",
        "source_snapshot_format": snapshot.get("format"),
        "defaults": {
            "default_edge_id": args.default_edge_id,
            "default_policy_mode": args.default_policy_mode,
            "default_preferred_uplink_id": args.default_preferred_uplink_id,
            "default_failover_uplink_id": args.default_failover_uplink_id,
            "skipped_statuses": sorted(skipped_statuses),
        },
        "summary": {
            "edges_count": len(DEFAULT_EDGES),
            "uplinks_count": len(DEFAULT_UPLINKS),
            "peers_count": len(peers),
            "skipped_peers_count": len(skipped_peers),
            "peer_runtime_state_count": len(peer_runtime_state),
            "routing_policy_count": len(routing_policies),
            "billing_records_count": len(billing_records),
            "events_count": len(events),
            "quarantine_count": len(quarantine),
            "status_distribution": status_distribution,
            "skipped_status_distribution": dict(
                Counter(row["status"] for row in skipped_peers)
            ),
        },
        "seed": {
            "edges": DEFAULT_EDGES,
            "uplinks": DEFAULT_UPLINKS,
        },
        "tables": {
            "peers": peers,
            "peer_runtime_state": peer_runtime_state,
            "peer_routing_policy": routing_policies,
            "billing_records": billing_records,
            "events": events,
            "peer_effective_routing": [],
            "edge_runtime_state": [],
            "uplink_runtime_state": [],
            "skipped_peers": skipped_peers,
        },
        "quarantine": quarantine,
    }


def main() -> int:
    args = parse_args()
    snapshot = read_snapshot(Path(args.input))
    plan = build_import_plan(snapshot, args)
    payload = json.dumps(plan, ensure_ascii=True, indent=2, sort_keys=True)
    if args.output:
        Path(args.output).write_text(payload + "\n")
    else:
        sys.stdout.write(payload + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
