#!/usr/bin/env python3
"""Build a parity report from JsTun legacy snapshot, import plan, and SQL emit meta."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a parity report from JsTun migration artifacts."
    )
    parser.add_argument(
        "--snapshot",
        required=True,
        help="Path to JSON snapshot generated by legacy_export.py",
    )
    parser.add_argument(
        "--import-plan",
        required=True,
        help="Path to JSON import plan generated by import_plan.py",
    )
    parser.add_argument(
        "--sql-meta",
        required=True,
        help="Path to JSON meta file generated by sql_emit.py",
    )
    parser.add_argument(
        "--output",
        help="Write parity report JSON to this file instead of stdout.",
    )
    return parser.parse_args()


def load_json(path: str) -> dict[str, Any]:
    return json.loads(Path(path).read_text())


def peer_status_distribution(snapshot: dict[str, Any]) -> dict[str, int]:
    counter = Counter()
    for row in snapshot.get("peers", []):
        source = row.get("source", {})
        status = source.get("status", "unknown")
        counter[status] += 1
    return dict(counter)


def imported_peer_lookup(import_plan: dict[str, Any]) -> set[str]:
    return {row["peer_id"] for row in import_plan["tables"]["peers"]}


def skipped_peer_lookup(import_plan: dict[str, Any]) -> set[str]:
    return {row["peer_id"] for row in import_plan["tables"]["skipped_peers"]}


def override_coverage(import_plan: dict[str, Any], peer_ids: set[str]) -> dict[str, Any]:
    label_overrides = import_plan.get("label_overrides") or {}
    type_overrides = import_plan.get("type_overrides") or {}
    covered_label = sum(1 for peer_id in label_overrides if peer_id in peer_ids)
    covered_type = sum(1 for peer_id in type_overrides if peer_id in peer_ids)
    return {
        "label_overrides_total": len(label_overrides),
        "label_overrides_covering_imported_peers": covered_label,
        "type_overrides_total": len(type_overrides),
        "type_overrides_covering_imported_peers": covered_type,
    }


def build_report(
    snapshot: dict[str, Any], import_plan: dict[str, Any], sql_meta: dict[str, Any]
) -> dict[str, Any]:
    imported_peers = imported_peer_lookup(import_plan)
    skipped_peers = skipped_peer_lookup(import_plan)
    snapshot_statuses = peer_status_distribution(snapshot)
    skipped_by_emit = sql_meta.get("skipped_by_emit", {})
    nullified_events = skipped_by_emit.get("events", [])

    nullified_event_types = dict(
        Counter(item.get("event_type", "unknown") for item in nullified_events)
    )

    billing_rows = import_plan["tables"]["billing_records"]
    billing_peer_ids = sorted({row["peer_id"] for row in billing_rows if row.get("peer_id")})
    billing_missing_fk = skipped_by_emit.get("billing_records", [])

    return {
        "format": "jstun-control-plane-parity-report/v1",
        "summary": {
            "legacy_peer_count": snapshot["summary"]["peer_count"],
            "imported_peer_count": import_plan["summary"]["peers_count"],
            "skipped_peer_count": import_plan["summary"]["skipped_peers_count"],
            "legacy_audit_event_count": snapshot["summary"]["audit_total_lines"],
            "emitted_event_count": sql_meta["emitted"]["events"],
            "nullified_event_peer_fk_count": len(nullified_events),
            "legacy_billing_count": snapshot["summary"]["billing_record_count"],
            "emitted_billing_count": sql_meta["emitted"]["billing_records"],
            "skipped_billing_count": len(billing_missing_fk),
            "quarantine_count": import_plan["summary"]["quarantine_count"],
        },
        "peer_parity": {
            "legacy_status_distribution": snapshot_statuses,
            "imported_status_distribution": import_plan["summary"]["status_distribution"],
            "skipped_status_distribution": import_plan["summary"]["skipped_status_distribution"],
            "imported_peer_ids": sorted(imported_peers),
            "skipped_peer_ids": sorted(skipped_peers),
        },
        "override_parity": {
            "label_overrides_total": snapshot["summary"]["label_override_count"],
            "type_overrides_total": snapshot["summary"]["type_override_count"],
            "label_overrides_covering_imported_peers": sum(
                1
                for peer_id in snapshot.get("label_overrides", {})
                if peer_id in imported_peers
            ),
            "type_overrides_covering_imported_peers": sum(
                1
                for peer_id in snapshot.get("type_overrides", {})
                if peer_id in imported_peers
            ),
        },
        "billing_parity": {
            "legacy_billing_peer_ids": billing_peer_ids,
            "skipped_billing_rows": billing_missing_fk,
        },
        "event_parity": {
            "nullified_event_types": nullified_event_types,
            "nullified_event_examples": nullified_events[:25],
        },
        "risks": {
            "quarantine_present": import_plan["summary"]["quarantine_count"] > 0,
            "billing_fk_loss_present": len(billing_missing_fk) > 0,
            "history_event_fk_loss_present": len(nullified_events) > 0,
        },
    }


def main() -> int:
    args = parse_args()
    snapshot = load_json(args.snapshot)
    import_plan = load_json(args.import_plan)
    sql_meta = load_json(args.sql_meta)
    report = build_report(snapshot, import_plan, sql_meta)
    payload = json.dumps(report, ensure_ascii=True, indent=2, sort_keys=True)
    if args.output:
        Path(args.output).write_text(payload + "\n")
    else:
        sys.stdout.write(payload + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
