#!/usr/bin/env python3
"""Emit Postgres SQL from a JsTun control-plane import plan."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


TABLE_COLUMNS: dict[str, list[str]] = {
    "edges": [
        "edge_id",
        "name",
        "role",
        "public_host",
        "client_interface",
        "client_subnet",
        "ru_egress",
        "state",
        "description",
    ],
    "uplinks": [
        "uplink_id",
        "edge_id",
        "name",
        "kind",
        "enabled",
        "description",
    ],
    "peers": [
        "peer_id",
        "label",
        "peer_type",
        "status",
        "public_key",
        "allowed_ip",
        "endpoint",
        "created_at",
        "pending_expires_at",
        "ttl_sec",
        "absolute_ttl_sec",
        "absolute_expires_at",
        "lk_token",
        "lk_token_created_at",
        "connected_at",
        "blocked_at",
        "block_reason",
        "removed_at",
        "remove_reason",
        "created_by",
        "updated_at",
    ],
    "peer_runtime_state": [
        "peer_id",
        "last_handshake_at",
        "last_handshake_unix",
        "rx_bytes",
        "tx_bytes",
        "real_ip",
        "active_uplink_id",
        "health_status",
        "health_note",
        "observed_at",
    ],
    "peer_routing_policy": [
        "peer_id",
        "ingress_edge_id",
        "policy_mode",
        "preferred_uplink_id",
        "failover_uplink_id",
        "updated_at",
        "updated_by",
        "change_reason",
    ],
    "billing_records": [
        "peer_id",
        "provider",
        "provider_order_id",
        "status_raw",
        "status_normalized",
        "amount_minor",
        "currency",
        "payment_url",
        "purpose",
        "created_at",
        "updated_at",
        "expires_at",
        "paid_at",
        "error_code",
        "error_message",
        "metadata",
    ],
    "events": [
        "event_type",
        "occurred_at",
        "actor_type",
        "actor_id",
        "peer_id",
        "edge_id",
        "uplink_id",
        "request_id",
        "reason",
        "old_value",
        "new_value",
        "metadata",
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Emit Postgres SQL from a JsTun control-plane import plan."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to JSON import plan generated by import_plan.py",
    )
    parser.add_argument(
        "--output",
        help="Write SQL to this file instead of stdout.",
    )
    parser.add_argument(
        "--ddl",
        help="Optional DDL file to prepend before emitted inserts.",
    )
    parser.add_argument(
        "--truncate-first",
        action="store_true",
        help="Emit truncate statements before inserts.",
    )
    return parser.parse_args()


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (dict, list)):
        return "'" + json.dumps(value, ensure_ascii=True).replace("'", "''") + "'::jsonb"
    return "'" + str(value).replace("'", "''") + "'"


def insert_block(table: str, rows: list[dict[str, Any]]) -> str:
    if not rows:
        return f"-- {table}: no rows\n"
    columns = TABLE_COLUMNS[table]
    values = []
    for row in rows:
        values.append(
            "(" + ", ".join(sql_literal(row.get(column)) for column in columns) + ")"
        )
    return (
        f"insert into {table} ({', '.join(columns)})\nvalues\n  "
        + ",\n  ".join(values)
        + "\non conflict do nothing;\n"
    )


def build_emit_payload(plan: dict[str, Any]) -> tuple[dict[str, list[dict[str, Any]]], dict[str, list[dict[str, Any]]]]:
    peer_ids = {row["peer_id"] for row in plan["tables"]["peers"]}

    emitted = {
        "edges": list(plan["seed"]["edges"]),
        "uplinks": list(plan["seed"]["uplinks"]),
        "peers": list(plan["tables"]["peers"]),
        "peer_runtime_state": list(plan["tables"]["peer_runtime_state"]),
        "peer_routing_policy": list(plan["tables"]["peer_routing_policy"]),
        "billing_records": [],
        "events": [],
    }
    skipped_by_emit = {
        "billing_records": [],
        "events": [],
    }

    for row in plan["tables"]["billing_records"]:
        if row.get("peer_id") not in peer_ids:
            skipped_by_emit["billing_records"].append(
                {
                    "reason": "peer_id_not_imported",
                    "peer_id": row.get("peer_id"),
                    "provider": row.get("provider"),
                    "provider_order_id": row.get("provider_order_id"),
                    "legacy_billing_order_id": row.get("legacy_billing_order_id"),
                }
            )
            continue
        emitted["billing_records"].append(row)

    for row in plan["tables"]["events"]:
        event = dict(row)
        if event.get("peer_id") and event["peer_id"] not in peer_ids:
            metadata = dict(event.get("metadata") or {})
            metadata["legacy_peer_id_raw"] = event["peer_id"]
            metadata["emit_peer_fk_reason"] = "peer_id_not_imported"
            event["metadata"] = metadata
            skipped_by_emit["events"].append(
                {
                    "reason": "peer_id_not_imported",
                    "peer_id": event.get("peer_id"),
                    "event_type": event.get("event_type"),
                    "occurred_at": event.get("occurred_at"),
                }
            )
            event["peer_id"] = None
        emitted["events"].append(event)

    return emitted, skipped_by_emit


def truncate_block() -> str:
    tables = [
        "events",
        "billing_records",
        "peer_runtime_state",
        "peer_routing_policy",
        "peers",
        "uplinks",
        "edges",
    ]
    return "truncate table " + ", ".join(tables) + " restart identity cascade;\n"


def build_sql(plan: dict[str, Any], ddl_text: str | None, truncate_first: bool) -> tuple[str, dict[str, Any]]:
    emitted, skipped_by_emit = build_emit_payload(plan)
    lines: list[str] = []
    lines.append("-- JsTun control-plane SQL emit")
    lines.append("-- source format: " + str(plan.get("format")))
    lines.append(
        "-- emitted summary: "
        + json.dumps(
            {
                "edges": len(emitted["edges"]),
                "uplinks": len(emitted["uplinks"]),
                "peers": len(emitted["peers"]),
                "peer_runtime_state": len(emitted["peer_runtime_state"]),
                "peer_routing_policy": len(emitted["peer_routing_policy"]),
                "billing_records": len(emitted["billing_records"]),
                "events": len(emitted["events"]),
                "skipped_billing_records": len(skipped_by_emit["billing_records"]),
                "events_with_nullified_peer_fk": len(skipped_by_emit["events"]),
            },
            sort_keys=True,
        )
    )
    lines.append("begin;")
    if ddl_text:
        lines.append("-- DDL prelude")
        lines.append(ddl_text.rstrip())
    if truncate_first:
        lines.append(truncate_block().rstrip())
    for table in [
        "edges",
        "uplinks",
        "peers",
        "peer_routing_policy",
        "peer_runtime_state",
        "billing_records",
        "events",
    ]:
        lines.append("")
        lines.append("-- " + table)
        lines.append(insert_block(table, emitted[table]).rstrip())
    lines.append("commit;")
    sql = "\n".join(lines) + "\n"
    meta = {
        "emitted": {key: len(value) for key, value in emitted.items()},
        "skipped_by_emit": skipped_by_emit,
    }
    return sql, meta


def main() -> int:
    args = parse_args()
    plan = json.loads(Path(args.input).read_text())
    if plan.get("format") != "jstun-control-plane-import-plan/v1":
        raise ValueError(f"unsupported import plan format: {plan.get('format')!r}")

    ddl_text = Path(args.ddl).read_text() if args.ddl else None
    sql, meta = build_sql(plan, ddl_text=ddl_text, truncate_first=args.truncate_first)
    if args.output:
        Path(args.output).write_text(sql)
        meta_path = Path(args.output).with_suffix(Path(args.output).suffix + ".meta.json")
        meta_path.write_text(json.dumps(meta, ensure_ascii=True, indent=2, sort_keys=True) + "\n")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
